[package]
name = "halp"
version = "0.1.0"
authors = ["porko"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.15"
cli-clipboard = "0.2.0"

